# deployment/docker-compose.yml
services:

  classifier_api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.classifier
    container_name: classifier_api
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models:ro          # modelos read-only
      - ../classifier_api:/app/classifier_api  # Mapea tu código de la API vivo
      - ../shared:/app/shared                  # Mapea códigos compartidos
    command: ["uvicorn", "classifier_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] # Activa el reload automático de FastAPI
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  detector_agent:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.detector
    container_name: detector_agent
    depends_on:
      classifier_api:
        condition: service_healthy
    volumes:
      - ../models:/app/models:ro
      - ../detector_agent:/app/detector_agent  # Mapea tu agente en vivo
      - ../shared:/app/shared
      - ../data:/app/data
      # TODO: montar dispositivo de camara si es necesario
      # devices:
      #   - /dev/video0:/dev/video0
    environment:
      - PYTHONUNBUFFERED=1
      - CLASSIFIER_HOST=http://classifier_api
      - CLASSIFIER_PORT=8000
    restart: unless-stopped

networks:
  default:
    name: fruit_ai_network
